name: flutter_online_cardgame
description: "A Flutter-based online card game with Firebase backend."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.1
  firebase_database: ^11.3.7
  cloud_functions: ^5.6.1
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  crypto: ^3.0.6
  html: ^0.15.6
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  web: ^1.1.1
  showcaseview: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 700